### ISSUE TITLE
Unknown type for deserialization when trying to get enum collection in C#

### ISSUE THREAD

**Issue by alexvab** [microsoft/kiota-dotnet#278]
Hello, I have an issue with the api endpoint (controller action) which return collection of C# enum as a json
this is my swagger.json file:
``` json 

{
  "openapi": "3.0.1",
  "info": {
    "title": "KiotaTestApi.WebApi",
    "version": "1.0"
  },
  "paths": {
    "/api/TestData/just-enums": {
      "get": {
        "tags": [
          "TestData"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "text/plain": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/KiotaTestApi.Models.Export.MyTaskStatus"
                  }
                }
              },
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/KiotaTestApi.Models.Export.MyTaskStatus"
                  }
                }
              },
              "text/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/KiotaTestApi.Models.Export.MyTaskStatus"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "KiotaTestApi.Models.Export.MyTaskStatus": {
        "enum": [
          "Pending",
          "InProgress",
          "Done"
        ],
        "type": "string"
      }
    }
  }
}

```

Here is my controller action definition 
```csharp
    /// <summary>
    /// Get task statuses
    /// </summary>
    /// <returns></returns>
    [HttpGet("just-enums")]
    [ProducesResponseType(StatusCodes.Status200OK)]
    public async Task<ActionResult<IReadOnlyCollection<MyTaskStatus>>> GetStatuses()

```

When I'm using Kiota ApiClient that has been generated using this swagger.json file above I get an exception when  GetAsync  method is executed 

```

System.InvalidOperationException: unknown type for deserialization System.Nullable`1[[KiotaTestApi.ApiClient.Models.MyTaskStatus, KiotaTestApi.ApiClient, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]
   at Microsoft.Kiota.Serialization.Json.JsonParseNode.GetCollectionOfPrimitiveValues[T]()+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at KiotaTestApi.ApiClient.Api.TestData.JustEnums.JustEnumsRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken) 

```
It seems like enum was handled as a primitive type in `GetCollectionOfPrimitiveValues` but there is no option for enum there:

``` csharp
...
if(genericType == TypeConstants.BooleanType)
                        yield return (T)(object)currentParseNode.GetBoolValue()!;
                    else if(genericType == TypeConstants.ByteType)
                        yield return (T)(object)currentParseNode.GetByteValue()!;
                    else if(genericType == TypeConstants.SbyteType)
                        yield return (T)(object)currentParseNode.GetSbyteValue()!;
                    else if(genericType == TypeConstants.StringType)
                        yield return (T)(object)currentParseNode.GetStringValue()!;
                    else if(genericType == TypeConstants.IntType)
                        yield return (T)(object)currentParseNode.GetIntValue()!;
                    else if(genericType == TypeConstants.FloatType)
                        yield return (T)(object)currentParseNode.GetFloatValue()!;
                    else if(genericType == TypeConstants.LongType)
                        yield return (T)(object)currentParseNode.GetLongValue()!;
                    else if(genericType == TypeConstants.DoubleType)
                        yield return (T)(object)currentParseNode.GetDoubleValue()!;
                    else if(genericType == TypeConstants.GuidType)
                        yield return (T)(object)currentParseNode.GetGuidValue()!;
                    else if(genericType == TypeConstants.DateTimeOffsetType)
                        yield return (T)(object)currentParseNode.GetDateTimeOffsetValue()!;
                    else if(genericType == TypeConstants.TimeSpanType)
                        yield return (T)(object)currentParseNode.GetTimeSpanValue()!;
                    else if(genericType == TypeConstants.DateType)
                        yield return (T)(object)currentParseNode.GetDateValue()!;
                    else if(genericType == TypeConstants.TimeType)
                        yield return (T)(object)currentParseNode.GetTimeValue()!;
                    else
                        throw new InvalidOperationException($"unknown type for deserialization {genericType.FullName}");

.....
```

This is my GetAsync method:

```csharp
 public async Task<List<MyTaskStatus?>?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<MyTaskStatus?>> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendPrimitiveCollectionAsync<MyTaskStatus?>(requestInfo, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.ToList();
        }
```

So I'm wondering is this a know issue, or it is something that not supported by Kiota? (I was using versions 1.12 and 1.13)

Please let me know if you need more information.

Thanks!

**Comment by andrueastman** [comment]
Resolved with https://github.com/microsoft/kiota-dotnet/pull/291
