### ISSUE TITLE
Kiota C# Client crashes on Blazor WASM

### ISSUE THREAD

**Issue by brad-technologik** [microsoft/kiota-dotnet#481]
### What are you generating using Kiota, clients or plugins?

API Client/SDK

### In what context or format are you using Kiota?

Nuget tool

### Client library/SDK language

Csharp

### Describe the bug

When I try and import my Kiota C# in a Blazor WASM Project, the page gets an error whenever the Kiota client is injected into a page:
```
ManagedError: One or more errors occurred. (Operation is not supported on this platform.)
```

### Expected behavior

Kiota C# client should work in Blazor. The error is kind of vague, but it may be related to multi threading which isn't supported in Blazor.

Given how Kiota and Blazor are both Microsoft products, I'd expect them work together.

### How to reproduce

```bash
dotnet new blazor -ai -int WebAssembly -n KiotaBlazorBug
cd KiotaBlazorBug/KiotaBlazorBug.Client
dotnet add package Microsoft.Kiota.Bundle
kiota generate --language=CSharp -d https://petstore3.swagger.io/api/v3/openapi.json -o ./Client -c PetStoreClient -n KiotaBlazorBug.Client
```
Add the following code to `Program.cs` (In *both* `KiotaBlazorBug/KiotaBlazorBug/Program.cs` and `KiotaBlazorBug/KiotaBlazorBug.Client`)

```cs
builder.Services.AddSingleton<PetStoreClient>(e =>
{
    var authProvider = new AnonymousAuthenticationProvider();
    // Create request adapter using the HttpClient-based implementation
    var adapter = new HttpClientRequestAdapter(authProvider);
    // Create the API client
    return new PetStoreClient(adapter);
});
```

Add the following line to `Counter.razor`

```cs
@inject PetStoreClient PetStoreClient
```

Run the project
```
cd ../KiotaBlazorBug
dotnet run
```

Visit http://localhost:5003/counter in your  Browser and observe the error and JS console.

### Open API description file

Any one. https://petstore3.swagger.io/api/v3/openapi.json is an example.

### Kiota Version

1.20.0+81bdb1bf13383a749f794d47926d09733d2d7be1

### Configuration

- OS: Mac OS 15.1 (24B83)

### Debug output

<details><summary>Click to expand log</summary>
```
blazor.web.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Operation is not supported on this platform.
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.Http.SocketsHttpHandler.set_Proxy(IWebProxy value)
   at Microsoft.Kiota.Http.HttpClientLibrary.KiotaClientFactory.GetDefaultHttpMessageHandler(IWebProxy proxy)
   at Microsoft.Kiota.Http.HttpClientLibrary.KiotaClientFactory.Create(HttpMessageHandler finalHandler, IRequestOption[] optionsForHandlers)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter..ctor(IAuthenticationProvider authenticationProvider, IParseNodeFactory parseNodeFactory, ISerializationWriterFactory serializationWriterFactory, HttpClient httpClient, ObservabilityOptions observabilityOptions)
   at Program.<>c.<<Main>$>b__0_0(IServiceProvider e) in /Users/brad/tmp/kiota-bug/KiotaBlazorBug/KiotaBlazorBug.Client/Program.cs:line 12
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=9.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=9.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeServiceProviderEngine.<>c__DisplayClass4_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass9_0.<CreatePropertyInjector>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType, IComponentRenderMode callerSpecifiedRenderMode, Nullable`1 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame[] frames, Int32 frameIndex, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()

```
</details>

**Comment by brad-technologik** [comment]
@baywet 

Can you re-open this bug? It's not resolved. 

I provided sufficient reproduction steps and I don't have the time to perform debugging to narrow down the root cause but I think it should remain in a backlog somewhere.

**Comment by baywet** [comment]
@brad-technologik can you at least take the time to run the last test I've suggested please?

**Comment by emilvberglind** [comment]
I'm running into the same issue. I did confirm that the `KiotaClientFactory.GetDefaultHttpMessageHandler` is indeed the problem since it would default to non-browser supported stuff. If I do this instead:

```
       var httpClient = KiotaClientFactory.Create(finalHandler: new HttpClientHandler { AllowAutoRedirect = false });
        var requestAdapter = new HttpClientRequestAdapter(authProvider, httpClient: httpClient)
        {
            BaseUrl = section["BaseUrl"],
        };
```

Then it works fine.

**Comment by baywet** [comment]
Thank you for the additional information.

My guess is that method is trying to return the [socketsHttpHandler](https://github.com/microsoft/kiota-dotnet/blob/6ac8f80a2a57c4efb81ed7339e55f0af5979be05/src/http/httpClient/KiotaClientFactory.cs#L189) which is not supported in this environment.

The [documentation](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=net-9.0#definition) would support this hypothesis because of the following attribute `[System.Runtime.Versioning.UnsupportedOSPlatform("browser")]`

Adding an additional compilation condition would probably fix this issue.

I've put together #512 as an attempt to fix that

**Comment by huhubun** [comment]
This still appears to be an issue for Blazor Interactive Auto applications, and it can be reproduced using version 1.17.1 of the package:

```bash
dotnet new blazor -int Auto -n KiotaBlazor
cd .\KiotaBlazor\KiotaBlazor.Client\
dotnet add package Microsoft.Kiota.Bundle -v 1.17.1
kiota generate --language=CSharp -d https://petstore3.swagger.io/api/v3/openapi.json -o ./Client -c PetStoreClient -n KiotaBlazor.Client
```

then, modify the `KiotaBlazor.Client/pages/Counter.razor` file:

```diff
@page "/counter"
- @rendermode InteractiveAuto
+ @rendermode InteractiveWebAssembly

<PageTitle>Counter</PageTitle>

<h1>Counter</h1>

<p role="status">Current count: @currentCount</p>

<button class="btn btn-primary" @onclick="IncrementCount">Click me</button>

@code {
    private int currentCount = 0;

    private void IncrementCount()
    {
        currentCount++;
    }

+    protected override void OnInitialized()
+    {
+        var authProvider = new Microsoft.Kiota.Abstractions.Authentication.AnonymousAuthenticationProvider();
+        var adapter = new Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter(authProvider);
+
+        var client = new PetStoreClient(adapter);
+    }
}
```

run the program and navigate to the `/counter` page. You can view the error messages in F12 Developer Tools:

```text
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Operation is not supported on this platform.
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.Http.SocketsHttpHandler.set_Proxy(IWebProxy value)
   at Microsoft.Kiota.Http.HttpClientLibrary.KiotaClientFactory.GetDefaultHttpMessageHandler(IWebProxy proxy)
   at Microsoft.Kiota.Http.HttpClientLibrary.KiotaClientFactory.Create(HttpMessageHandler finalHandler, IRequestOption[] optionsForHandlers)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter..ctor(IAuthenticationProvider authenticationProvider, IParseNodeFactory parseNodeFactory, ISerializationWriterFactory serializationWriterFactory, HttpClient httpClient, ObservabilityOptions observabilityOptions)
   at KiotaBlazor.Client.Pages.Counter.OnInitialized() 
```

**Comment by baywet** [comment]
Thank you for the additional information.

What's the moniker/tfm for those auto projects? (I wasn't aware you could target "vehicles" in dotnet)

Should we add additional compilation directives here?
https://github.com/microsoft/kiota-dotnet/blob/273e23072904ded60e22a434013475975d80049a/src/http/httpClient/KiotaClientFactory.cs#L256

Can you create another issue dedicated to the auto scenario?

**Comment by manuelelucchi** [comment]
@baywet it's still an issue in dotnet 10 blazor wasm (standalone app) 
It seems like the !BROWSER is [gone ](https://github.com/microsoft/kiota-dotnet/blob/6ac8f80a2a57c4efb81ed7339e55f0af5979be05/src/http/httpClient/KiotaClientFactory.cs#L188)

**Comment by baywet** [comment]
@manuelelucchi thanks for reporting this. Can you confirm whether your app is currently targeting `net8.0-browser` or `net10.0-browser`?

The `BROWSER` directive was not removed from source, but v2 added a `net10.0` asset without adding a matching `net10.0-browser` asset. That means `net10.0-browser` consumers can resolve the non-browser `net10.0` assembly, where `BROWSER` is not defined, and hit the `SocketsHttpHandler` path again. See #708

If you have a chance, a PR adding `net10.0-browser` to the HTTP csproj target frameworks would likely address this and prevent browser apps from selecting the non-browser asset.
