### ISSUE TITLE
Unable to get types from assembly which depend on Kiota or kiota.* dll.

### ISSUE THREAD

**Issue by thompson-tomo** [microsoft/kiota-dotnet#500]
My application leverages a plugin architecture where in which dll's can be dynamically added to the application for different integrations. These plugins are loaded using "Assembly.LoadFile" however when it attempts to load Microsoft.Kiota.* (excluding the abstractions) package it will fail to load as can't get the types. It will also cause any library dependent on Microsoft Kiota to also fail resulting in my plugin not being loadable.

The exception i am encountering is:
Message:
```
{"Unable to load one or more of the requested types.\r\nCould not load file or assembly 'Microsoft.Kiota.Http.HttpClientLibrary, Version=1.16.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified."}
```

StackTrace
```
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Skidata.Dashboard.Connector.ConnectorResolver.LoadConnector[T1](List`1 options, String folder) in C:\Users\thja\Documents\Repos\dashboard\interface\panel-connector\src\Skidata.Dashboard.Connector\ConnectorResolver.cs:line 27
``` 

Loader Exceptions
```
{"Could not load file or assembly 'Microsoft.Kiota.Http.HttpClientLibrary, Version=1.16.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.":"Microsoft.Kiota.Http.HttpClientLibrary, Version=1.16.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"}
``` 

Application is being compiled for dotnet 8
libary: 1.16.1

**Comment by baywet** [comment]
Hi @thompson-tomo 
Thank you for using kiota and for reaching out.

I'd like to mention that we're operating with a reduced team at the moment, expect delays in responses, thank you for your patience!

Can you ensure the dll is present with the deployment and in the expected location for your assembly loading implementation to find it please?

Do you have other modules that depend on additional dependencies and are loading fine? Can you compare the references of the package (and the copy mechanisms)

**Comment by thompson-tomo** [comment]
No worries especially as I am also on leave atm. 

Yes I can confirm file is present in the folder and In fact to achieve the plugin architecture I am scanning the configured folder for all dll's which is how I determine what could be loaded. With the folder being a clone of publish output.

What I found is that the abstraction lib will load without issue but not the others. At the same time Std.UriTemplate has no issue loading. One of my other plugin is operating without issue with a dependency on Brainboxes.IO.

**Comment by baywet** [comment]
Thank you for the additional information.

Is http client the only one that doesn't load? or do you also have issues with serialization JSON/Text/Form/Multipart?

**Comment by thompson-tomo** [comment]
Also issues with serilaztion. I have a dependency on the bundle & only abstractions will load everything else fails.

**Comment by baywet** [comment]
Thank you for the additional information.

Does the issue happens only in production? or also when you try to debug the application in the IDE? (the linkage is a bit different between the two)

**Comment by thompson-tomo** [comment]
Issue Also occurs when running my app in the visual studio debugger. Note I have tried to load both the published output & also the bin output but same result.

**Comment by baywet** [comment]
Thank you for the additional information.

Is your app using any trimming? are the hashes of the dlls in the source package and the published result the same? (trying to check whether anything might have been tempered by a custom build process here)

Are you able to share a minimal reproduction repository?

Thanks!

**Comment by thompson-tomo** [comment]
Hi @baywet sorry it took longer than expected as i have been tied up with other tasks. :( Please find attached 2 examples of behaviour which is resulting in the issue: https://github.com/thompson-tomo/kiota-abstractions-dotnet/commit/ed89471f63a98c6a7f87a430cd1862c17f7e8f5f

Note abstractions appears to work for me but not the other kiota libraries.

**Comment by baywet** [comment]
Thank you for the additional information.

I've spent quite some time getting the unit test to build/run.

Here are a few patches that I think you should apply to that branch to make things easier.

[0001-fix-repro-test-project-build-configuration.patch](https://github.com/user-attachments/files/18398215/0001-fix-repro-test-project-build-configuration.patch)
[0001-chore-assembly-key-for-release.patch](https://github.com/user-attachments/files/18398216/0001-chore-assembly-key-for-release.patch)
[0001-fix-path-combination-on-linux.patch](https://github.com/user-attachments/files/18398217/0001-fix-path-combination-on-linux.patch)

Then something struck me, this test CANNOT work since

```bash
ls /workspaces/kiota-abstractions-dotnet/tests/Github.500/bin/Debug/net9.0/../../../../../src/bundle/bin/Release/net8.0/*.dll
```


returns 

```
/workspaces/kiota-abstractions-dotnet/tests/Github.500/bin/Debug/net9.0/../../../../../src/bundle/bin/Release/net8.0/Microsoft.Kiota.Abstractions.dll
/workspaces/kiota-abstractions-dotnet/tests/Github.500/bin/Debug/net9.0/../../../../../src/bundle/bin/Release/net8.0/Microsoft.Kiota.Bundle.dll
/workspaces/kiota-abstractions-dotnet/tests/Github.500/bin/Debug/net9.0/../../../../../src/bundle/bin/Release/net8.0/Microsoft.Kiota.Http.HttpClientLibrary.dll
/workspaces/kiota-abstractions-dotnet/tests/Github.500/bin/Debug/net9.0/../../../../../src/bundle/bin/Release/net8.0/Microsoft.Kiota.Serialization.Form.dll
/workspaces/kiota-abstractions-dotnet/tests/Github.500/bin/Debug/net9.0/../../../../../src/bundle/bin/Release/net8.0/Microsoft.Kiota.Serialization.Json.dll
/workspaces/kiota-abstractions-dotnet/tests/Github.500/bin/Debug/net9.0/../../../../../src/bundle/bin/Release/net8.0/Microsoft.Kiota.Serialization.Multipart.dll
/workspaces/kiota-abstractions-dotnet/tests/Github.500/bin/Debug/net9.0/../../../../../src/bundle/bin/Release/net8.0/Microsoft.Kiota.Serialization.Text.dll
```

Which to start with, does not contain std.uritemplate, one of the main dependency. My guess is that your production code is facing a similar issue, where due to its design and the assemblies being copied, it's missing a dependency of the http package (or possible more).

Lastly, please have a look at the [remarks section regarding the assembly load context](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assembly.loadfile?view=net-8.0#system-reflection-assembly-loadfile(system-string))

Let us know if you have any additional comments or questions.

**Comment by thompson-tomo** [comment]
Thanks @baywet for the feedback I hope to come back to this in the coming days and respond about the patches. I think the important differentiating scenario between the test & my prod is that in prod I am deploying the contents of the publish folder so doubt that my issue in prod is missing files as they should all be there. But will review the unit test etc to ensure all is accurate with repo etc.

Also my production code is being shipped as a single file, self contained exe running net 8 and my dll also published as net 8 so should not be an issue of version and anyway as long as dll is same or older framework then it is compatible.
